server:
  port: 80
  servlet:
    context-path: /
  
spring:
   datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_sports
      username: root
      password: 134176
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
   thymeleaf:
    cache: false